# Generated by Django 4.2.4 on 2023-08-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orderitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order_price',
            field=models.IntegerField(null=True),
        ),
    ]
