# Generated by Django 4.2.4 on 2023-08-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='item_totalprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
