name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
  

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          cd drfdcommerce
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    #- name: Run Tests
     # run: |
      #  python manage.py test
